In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [9]:
df=pd.read_csv("netflix_titles_2021.csv")

In [72]:
df.tail(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
700,s701,TV Show,Record of Ragnarok,NaN,"Miyuki Sawashiro, Tomoyo Kurosawa, Tomokazu Se...",NaN,"June 17, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows","Before eradicating humankind from the world, t..."
397,s398,TV Show,Feels Like Ishq,NaN,"Radhika Madan, Amol Parashar, Rohit Saraf, Kaj...",NaN,"July 23, 2021",2021,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Short films follow young adults as they naviga...
503,s504,TV Show,The Mire,Jan Holoubek,"Andrzej Seweryn, Dawid Ogrodnik, Zofia Wichłac...",Poland,"July 7, 2021",2021,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas","In an early-'80s Polish town, a prostitute and..."
35,s36,Movie,The Father Who Moves Mountains,Daniel Sandu,"Adrian Titieni, Elena Purea, Judith State, Val...",NaN,"September 17, 2021",2021,TV-MA,110 min,"Dramas, International Movies, Thrillers",When his son goes missing during a snowy hike ...
272,s273,TV Show,Fast & Furious Spy Racers,NaN,"Tyler Posey, Charlet Chung, Jorge Diaz, Camill...",United States,"August 13, 2021",2021,TV-Y7,5 Seasons,Kids' TV,A government agency recruits teen driver Tony ...
82,s83,TV Show,Lucifer,NaN,"Tom Ellis, Lauren German, Kevin Alejandro, D.B...",United States,"September 10, 2021",2021,TV-14,6 Seasons,"Crime TV Shows, TV Comedies, TV Dramas","Bored with being the Lord of Hell, the devil r..."
1370,s1371,Movie,The Dig,Simon Stone,"Carey Mulligan, Ralph Fiennes, Lily James, Joh...",United Kingdom,"January 29, 2021",2021,PG-13,113 min,"Dramas, International Movies","On the eve of World War II, a British widow hi..."
912,s913,Movie,The Circle - The Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",NaN,"May 7, 2021",2021,TV-14,35 min,Comedies,"Stars of ""The Circle"" drop by to discuss Seaso..."
696,s697,TV Show,Black Summer,NaN,"Jaime King, Justin Chu Cary, Christine Lee, Sa...","Canada, United States","June 17, 2021",2021,TV-MA,2 Seasons,"TV Action & Adventure, TV Dramas, TV Horror","In the dark, early days of a zombie apocalypse..."
833,s834,TV Show,Black Space,NaN,"Guri Alfi, Shai Avivi, Assi Levy, Reut Alush, ...",Israel,"May 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A rogue detective with unorthodox means leads ...
734,s735,TV Show,Lupin,NaN,"Omar Sy, Ludivine Sagnier, Clotilde Hesme, Nic...","France, United States","June 11, 2021",2021,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Act...","Inspired by the adventures of Arsène Lupin, ge..."
1301,s1302,TV Show,Behind Her Eyes,NaN,"Simona Brown, Eve Hewson, Tom Bateman, Robert ...",United Kingdom,"February 17, 2021",2021,TV-MA,1 Season,"British TV Shows, International TV Shows, TV D...",A single mother enters a world of twisted mind...
1012,s1013,TV Show,Luis Miguel - The Series,NaN,"Diego Boneta, Juan Pablo Zurita, Camila Sodi, ...",Mexico,"April 19, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",This series dramatizes the life story of Mexic...
403,s404,TV Show,The Movies That Made Us,NaN,NaN,United States,"July 23, 2021",2021,TV-MA,2 Seasons,Docuseries,These blockbusters brought us together and gav...
570,s571,Movie,Dynasty Warriors,Chow Hin Yeung Roy,"Wang Kai, Louis Koo, Han Geng, Tony Yang, Cari...",NaN,"July 1, 2021",2021,TV-14,118 min,"Action & Adventure, International Movies","Warlords, warriors and statesmen wage a battle..."
959,s960,Movie,The Disciple,Chaitanya Tamhane,"Aditya Modak, Arun Dravid, Sumitra Bhave, Deep...",India,"April 30, 2021",2021,TV-MA,128 min,"Dramas, Independent Movies, International Movies","Self-doubt, sacrifice and struggle converge in..."
546,s547,TV Show,You Are My Spring,NaN,"Seo Hyun-jin, Kim Dong-wook, Yoon Bak, Nam Gyu...",NaN,"July 6, 2021",2021,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A hotel concierge and a psychiatrist with trau...
660,s661,TV Show,Black Lightning,NaN,"Cress Williams, James Remar, Marvin 'Krondon' ...",United States,"June 19, 2021",2021,TV-14,4 Seasons,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",School principal and retired superhero Jeffers...
370,s371,TV Show,Outer Banks,NaN,"Chase Stokes, Madelyn Cline, Madison Bailey, J...",United States,"July 30, 2021",2021,TV-MA,2 Seasons,"TV Action & Adventure, TV Dramas, Teen TV Shows","On an island of haves and have-nots, teen John..."
993,s994,TV Show,Shadow and Bone,NaN,"Jessie Mei Li, Archie Renaux, Ben Barnes, Fred...",United States,"April 23, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",Dark forces conspire against orphan mapmaker A...

In [73]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8419,s8420,Movie,The Memphis Belle: A Story of a\nFlying Fortress,William Wyler,NaN,United States,"March 31, 2017",1944,TV-PG,40 min,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...
8436,s8437,Movie,The Negro Soldier,Stuart Heisler,NaN,United States,"March 31, 2017",1944,TV-14,40 min,"Classic Movies, Documentaries",This documentary urged African Americans to en...
8640,s8641,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
1331,s1332,TV Show,Five Came Back: The Reference Films,NaN,NaN,United States,"February 9, 2021",1945,TV-MA,1 Season,TV Shows,This collection includes 12 World War II-era p...

In [11]:
df.sample(10) #taking the sample of dataset

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8085,s8086,TV Show,Station Horizon,NaN,"Bernard Yerlès, Roland Vouilloz, Gaspard Boesc...",Switzerland,"September 1, 2016",2015,TV-MA,1 Season,"International TV Shows, TV Comedies, TV Dramas","Ex-con Joris returns to his Swiss hometown, a ..."
1948,s1949,TV Show,Van Helsing,NaN,"Kelly Overton, Jonathan Scarfe, Christopher He...",United States,"September 27, 2020",2019,TV-MA,4 Seasons,"International TV Shows, TV Action & Adventure,...","After three years in a coma, Vanessa awakens t..."
3192,s3193,TV Show,Eastsiders,NaN,"Kit Williamson, Van Hansis, Constance Wu, Matt...",United States,"December 1, 2019",2018,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Cal turns to his friends for help through a hi...
7831,s7832,Movie,Rampant,Kim Sung-hoon,"Hyun Bin, Jang Dong-gun, Jo Woo-jin, Jeong Man...",South Korea,"May 26, 2019",2018,TV-MA,122 min,"Action & Adventure, Horror Movies, Internation...",When Prince Lee Cheong returns to Joseon after...
1981,s1982,Movie,Whipped,Chandra Liow,"Andovi da Lopez, Jovial da Lopez, Chandra Liow...",Indonesia,"September 18, 2020",2020,TV-14,98 min,"Comedies, International Movies, Romantic Movies",Four buddies attend a class taught by a love g...
579,s580,Movie,Midnight Run,Martin Brest,"Robert De Niro, Charles Grodin, Yaphet Kotto, ...",United States,"July 1, 2021",1988,R,126 min,"Action & Adventure, Classic Movies, Comedies",A cop-turned-bounty hunter runs into trouble a...
4280,s4281,Movie,Imperfect,Steve Cheng,"Edwin Goh, Ian Fang Weijie, Phua Yida, Kimberl...",Singapore,"December 20, 2018",2012,TV-MA,95 min,"Action & Adventure, International Movies","After a brawl lands him in a Boys’ Home, a tee..."
4734,s4735,Movie,Tamasha,Imtiaz Ali,"Ranbir Kapoor, Deepika Padukone, Piyush Mishra...",India,"August 2, 2018",2015,TV-14,133 min,"Dramas, International Movies, Romantic Movies","Meeting while on vacation, Ved and Tara sense ..."
4714,s4715,Movie,Brij Mohan Amar Rahe,Nikhil Nagesh Bhat,"Arjun Mathur, Nidhi Singh, Manav Vij, Sheetal ...",India,"August 4, 2018",2018,TV-MA,100 min,"Comedies, Dramas, International Movies",Faking his death to escape the realities of hi...
4336,s4337,Movie,Crossroads: One Two Jaga,Nam Ron,"Zahiril Adzim, Ario Bayu, Asmara Abigail, Rosd...",Malaysia,"December 1, 2018",2018,TV-14,81 min,"Dramas, International Movies","In Kuala Lumpur, an abused domestic worker tri..."

In [12]:
df.shape # it shows the shape of dataset

(8807, 12)

In [14]:
df.columns # it shows the columns  in the dataset

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [15]:
df.info() # it shows the data type of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [17]:
df.describe()# it shows the mean meadian mode percentails

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [21]:
df.isnull().sum() # it shows the null data in a data set

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [24]:
df.duplicated() # it shows the duplicate data in the dataset

0       False
1       False
2       False
3       False
4       False
        ...
8802    False
8803    False
8804    False
8805    False
8806    False
Length: 8807, dtype: bool

In [25]:
df.loc[10:20] # it shows the range of data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
14,s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
19,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,NaN,NaN,"September 22, 2021",2021,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...","In the late 1970s, an accused serial rapist cl..."

In [31]:
df.type.value_counts() #IT SHOWS THE VALUE OF THE DATASET

Movie      6131
TV Show    2676
Name: type, dtype: int64

In [65]:
df.groupby(by=["director","title"]).size() # it shows the grouped items in the dataset

director             title
A. L. Vijay          Abhinetri                1
                     Watchman                 1
A. Raajdheep         Asura Guru               1
A. Salaam            Salaakhen                1
A.R. Murugadoss      Sarkar                   1
                                             ..
Óskar Thór Axelsson  Ég man þig               1
Ömer Faruk Sorak     Aşk Tesadüfleri Sever    1
                     G.O.R.A                  1
Şenol Sönmez         Hayat Öpücügü            1
                     Kill Me If You Dare      1
Length: 6173, dtype: int64

In [74]:
df.sort_values(by="release_year",inplace=True,ascending=False) # it udes to sort the dataset
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
993,s994,TV Show,Shadow and Bone,NaN,"Jessie Mei Li, Archie Renaux, Ben Barnes, Fred...",United States,"April 23, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",Dark forces conspire against orphan mapmaker A...
361,s362,TV Show,Charmed,NaN,"Madeleine Mantock, Sarah Jeffery, Melonie Diaz...",United States,"July 31, 2021",2021,TV-14,3 Seasons,"TV Dramas, TV Sci-Fi & Fantasy","After their mother’s tragic death, a trio of s..."
691,s692,TV Show,So Not Worth It,NaN,"Park Se-wan, Shin Hyeon-seung, Choi Young-jae,...",NaN,"June 18, 2021",2021,TV-14,1 Season,"International TV Shows, TV Comedies","New friends, new loves and new experiences mix..."
74,s75,TV Show,The World's Most Amazing Vacation Rentals,NaN,NaN,NaN,"September 14, 2021",2021,TV-PG,2 Seasons,Reality TV,"With an eye for every budget, three travelers ..."
487,s488,TV Show,The Cook of Castamar,NaN,"Michelle Jenner, Roberto Enríquez, Hugo Silva,...",NaN,"July 9, 2021",2021,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, Spa...","In 1720 Madrid, a talented cook catches the ey..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...